export const IP_SEARCH_SERVICE = 'IP_SEARCH_SERVICE';
export const RECEIVE_IP_SEARCH = 'RECEIVE_IP_SEARCH';
export const ID_SEARCH_SERVICE = 'ID_SEARCH_SERVICE';
export const RECEIVE_ID_SEARCH = 'RECEIVE_ID_SEARCH';
export const HISTORYTODAY_SEARCH_SERVICE = 'HISTORYTODAY_SEARCH_SERVICE';
export const RECEIVE_HISTORYTODAY_SEARCH = 'RECEIVE_HISTORYTODAY_SEARCH';